name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies
      run: sudo apt-get install -y libgtk-3-dev

    - name: Install deadbeef headers
      run: |
        sudo mkdir -p /usr/local/include/deedbeef
        cd /usr/local/include/deedbeef
        sudo curl -O https://raw.githubusercontent.com/DeaDBeeF-Player/deadbeef/master/plugins/gtkui/gtkui_api.h
        sudo curl -O https://raw.githubusercontent.com/DeaDBeeF-Player/deadbeef/master/deadbeef.h

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into deadbeef-library subdirectory
      uses: actions/checkout@v2
      path: deadbeef-library

    - name: Check out musiclib-grpc into an adjacent subdirectory
      uses: actions/checkout@v2
      repository: mctofu/musiclib-grpc
      path: musiclib-grpc

    - name: Cache go modules
      uses: actions/cache@v2
      env:
        cache-name: cache-go-modules
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}

    - name: Build cgo client
      working-directory: ./musiclib-grpc
      run: ./cgo.sh

    - name: Build deadbeef-library
      working-directory: ./deadbeef-library
      run: ./build.sh
